<?php

namespace Database\Seeders;

use App\Models\Movie;
use Illuminate\Database\Seeder;

class MoviesSeeder extends Seeder
{
    public function run(): void
    {
        Movie::insert([
            [
                'title' => 'Incepcja',
                'description' => 'Złodziej, który włamuje się do umysłów, ma za zadanie zasadzić ideę w umyśle osoby.',
                'category_id' => 8,
                'director' => 'Christopher Nolan',
                'release_year' => 2010,
                'duration' => 148,
                'rate' => 8.8,
                'img_path' => 'img/incepcja.jpg',
                'video_path' => 'YoHD9XEInc0',
                'price_day' => 15.00,
                'available' => 'dostępny'
            ],
            [
                'title' => 'Interstellar',
                'description' => 'Astronauta próbuje przetrwać na Marsie po zostaniu uznany za martwego.',
                'category_id' => 9,
                'director' => 'Christopher Nolan',
                'release_year' => 2014,
                'duration' => 169,
                'rate' => 8.6,
                'img_path' => 'img/interstellar.jpg',
                'video_path' => 'zSWdZVtXT7E',
                'price_day' => 15.00,
                'available' => 'dostępny'
            ],
            [
                'title' => 'Matrix',
                'description' => 'Haker komputerowy odkrywa prawdziwą naturę swojej rzeczywistości i swoją rolę w wojnie przeciwko jej kontrolerom.',
                'category_id' => 9,
                'director' => 'Lana Wachowski',
                'release_year' => 1999,
                'duration' => 136,
                'rate' => 8.7,
                'img_path' => 'img/matrix.jpg',
                'video_path' => 'vKQi3bBA1y8',
                'price_day' => 10.00,
                'available' => 'dostępny'
            ],
            [
                'title' => 'Forrest Gump',
                'description' => 'Prosta historia mężczyzny, który przypadkiem bierze udział w ważnych wydarzeniach historycznych.',
                'category_id' => 3,
                'director' => 'Robert Zemeckis',
                'release_year' => 1994,
                'duration' => 142,
                'rate' => 8.8,
                'img_path' => 'img/forrest_gump.jpg',
                'video_path' => 'bLvqoHBptjg',
                'price_day' => 9.00,
                'available' => 'dostępny'
            ],
            [
                'title' => 'Fight Club',
                'description' => 'Mężczyzna walczy przeciwko swojemu alter-ego w brutalnych walkach na pięści.',
                'category_id' => 8,
                'director' => 'David Fincher',
                'release_year' => 1999,
                'duration' => 139,
                'rate' => 8.8,
                'img_path' => 'img/fight_club.jpg',
                'video_path' => 'SUXWAEX2jlg',
                'price_day' => 12.00,
                'available' => 'dostępny'
            ],
            [
                'title' => 'Pulp Fiction',
                'description' => 'Gangsterzy, bokserzy i inne postacie splatają się w skomplikowanej fabule.',
                'category_id' => 1,
                'director' => 'Quentin Tarantino',
                'release_year' => 1994,
                'duration' => 154,
                'rate' => 8.9,
                'img_path' => 'img/pulp_fiction.jpg',
                'video_path' => 's7EdQ4FqbhY',
                'price_day' => 11.00,
                'available' => 'dostępny'
            ],
            [
                'title' => 'Shutter Island',
                'description' => 'Detektyw próbuje rozwikłać zagadkę zaginięcia pacjentki z zamkniętego szpitala psychiatrycznego.',
                'category_id' => 18,
                'director' => 'Martin Scorsese',
                'release_year' => 2010,
                'duration' => 138,
                'rate' => 8.2,
                'img_path' => 'img/shutter_island.jpg',
                'video_path' => '5iaYLCiq5RM',
                'price_day' => 13.00,
                'available' => 'dostępny'
            ],
            [
                'title' => 'Szeregowiec Ryan',
                'description' => 'Misja ratunkowa podczas II wojny światowej, aby znaleźć i uratować spadochroniarza.',
                'category_id' => 15,
                'director' => 'Steven Spielberg',
                'release_year' => 1998,
                'duration' => 169,
                'rate' => 8.6,
                'img_path' => 'img/szeregowiec_ryan.webp',
                'video_path' => 'zwhP5b4tD6g',
                'price_day' => 10.00,
                'available' => 'dostępny'
            ],
            [
                'title' => 'Władca Pierścieni: Powrót króla',
                'description' => 'Ostatnia część epickiej trylogii o walce dobra ze złem o losy Śródziemia.',
                'category_id' => 4,
                'director' => 'Peter Jackson',
                'release_year' => 2003,
                'duration' => 201,
                'rate' => 8.9,
                'img_path' => 'img/wladca_pierscieni.jpg',
                'video_path' => 'r5X-hFf6Bwo',
                'price_day' => 14.00,
                'available' => 'dostępny'
            ],
            [
                'title' => 'Avatar',
                'description' => 'Opowieść o konflikcie na dystansowej planecie między ludźmi a miejscowymi Na vi.',
                'category_id' => 9,
                'director' => 'James Cameron',
                'release_year' => 2009,
                'duration' => 162,
                'rate' => 7.8,
                'img_path' => 'img/avatar.webp',
                'video_path' => '5PSNL1qE6VY',
                'price_day' => 13.00,
                'available' => 'dostępny'
            ],
            [
                'title' => 'The Godfather',
                'description' => 'Opowieść o władzy, lojalności i okrutnych realiach gangsterskiej rodziny Corleone.',
                'category_id' => 1,
                'director' => 'Francis Ford Coppola',
                'release_year' => 1972,
                'duration' => 175,
                'rate' => 9.2,
                'img_path' => 'img/the_godfather.jpg',
                'video_path' => 'sY1S34973zA',
                'price_day' => 15.00,
                'available' => 'dostępny'
            ],
            [
                'title' => 'Gladiator',
                'description' => 'Były rzymski generał stara się pomścić swoją rodzinę, zabitych przez skorumpowanego cesarza.',
                'category_id' => 15,
                'director' => 'Ridley Scott',
                'release_year' => 2000,
                'duration' => 155,
                'rate' => 8.5,
                'img_path' => 'img/gladiator.jpg',
                'video_path' => 'owK1qxDselE',
                'price_day' => 13.00,
                'available' => 'dostępny'
            ],
            [
                'title' => 'The Shawshank Redemption',
                'description' => 'Mężczyzna niesłusznie skazany na dożywocie szuka sposobu na przetrwanie i ostatecznie na wolność.',
                'category_id' => 3,
                'director' => 'Frank Darabont',
                'release_year' => 1994,
                'duration' => 142,
                'rate' => 9.3,
                'img_path' => 'img/shawshank_redemption.jpg',
                'video_path' => '6hB3S9bIaco',
                'price_day' => 12.00,
                'available' => 'dostępny'
            ],
            [
                'title' => 'The Dark Knight',
                'description' => 'Batman staje przeciwko psychopatycznemu złoczyńcy, Jokerowi, który chce zdominować Gotham City.',
                'category_id' => 8,
                'director' => 'Christopher Nolan',
                'release_year' => 2008,
                'duration' => 152,
                'rate' => 9.0,
                'img_path' => 'img/the_dark_knight.jpg',
                'video_path' => 'EXeTwQWrcwY',
                'price_day' => 13.00,
                'available' => 'dostępny'
            ],
            [
                'title' => 'The Great Gatsby',
                'description' => 'Młody pisarz zostaje wciągnięty w świat luksusu i dekadencji bogatego Jaya Gatsby’ego w latach 20.',
                'category_id' => 3,
                'director' => 'Baz Luhrmann',
                'release_year' => 2013,
                'duration' => 143,
                'rate' => 7.3,
                'img_path' => 'img/the_great_gatsby.jpg',
                'video_path' => 'rARN6agiW7o',
                'price_day' => 11.00,
                'available' => 'dostępny'
            ],
            [
                'title' => 'Life of Pi',
                'description' => 'Młody chłopiec przetrwał katastrofę na morzu z towarzyszącym mu nieoczekiwanym pasażerem, bengalskim tygrysem.',
                'category_id' => 7,
                'director' => 'Ang Lee',
                'release_year' => 2012,
                'duration' => 127,
                'rate' => 7.9,
                'img_path' => 'img/life_of_pi.jpg',
                'video_path' => 'mZEZ35Fhvuc',
                'price_day' => 10.00,
                'available' => 'dostępny'
            ],
            [
                'title' => 'Jurassic Park',
                'description' => 'Grupa naukowców zwiedza park tematyczny z klonowanymi dinozaurami, co prowadzi do katastrofy.',
                'category_id' => 2,
                'director' => 'Steven Spielberg',
                'release_year' => 1993,
                'duration' => 127,
                'rate' => 8.1,
                'img_path' => 'img/jurassic_park.jpg',
                'video_path' => 'lc0UehYemQA',
                'price_day' => 9.00,
                'available' => 'dostępny'
            ],
            [
                'title' => 'Schindler\'s List',
                'description' => 'Historia niemieckiego biznesmena, który ratuje życie ponad tysiąca Żydów podczas Holokaustu.',
                'category_id' => 12,
                'director' => 'Steven Spielberg',
                'release_year' => 1993,
                'duration' => 195,
                'rate' => 8.9,
                'img_path' => 'img/schindlers_list.jpg',
                'video_path' => 'gG22XNhtnoY',
                'price_day' => 11.00,
                'available' => 'dostępny'
            ],
            [
                'title' => 'Blade Runner 2049',
                'description' => 'Młody łowca androidów odkrywa długo skrywaną tajemnicę, która może zagrozić całemu społeczeństwu.',
                'category_id' => 9,
                'director' => 'Denis Villeneuve',
                'release_year' => 2017,
                'duration' => 164,
                'rate' => 8.0,
                'img_path' => 'img/blade_runner_2049.jpg',
                'video_path' => 'gCcx85zbxz4',
                'price_day' => 12.00,
                'available' => 'dostępny'
            ],
            [
                'title' => 'Moonlight',
                'description' => 'Chiron, chłopiec z trudnej dzielnicy Miami, próbuje znaleźć swoje miejsce w świecie, zmagając się z problemami domowymi i tożsamością seksualną.',
                'category_id' => 3,
                'director' => 'Barry Jenkins',
                'release_year' => 2016,
                'duration' => 111,
                'rate' => 7.4,
                'img_path' => 'img/moonlight.jpg',
                'video_path' => '9NJj12tJzqc',
                'price_day' => 10.00,
                'available' => 'dostępny'
            ],
            [
                'title' => 'Mad Max: Fury Road',
                'description' => 'Max Rockatansky wyrusza na pustynię z buntującą się Furiosą, która chce przetransportować pięć żon despotycznego władcy do bezpiecznego miejsca.',
                'category_id' => 1,
                'director' => 'George Miller',
                'release_year' => 2015,
                'duration' => 120,
                'rate' => 8.1,
                'img_path' => 'img/mad_max_fury_road.jpg',
                'video_path' => 'hEJnMQG9ev8',
                'price_day' => 10.00,
                'available' => 'dostępny'
            ],
            [
                'title' => 'Arrival',
                'description' => 'Gdy tajemnicze obiekty latające pojawiają się na całym świecie, lingwistka jest zatrudniona do próby komunikacji z obcymi.',
                'category_id' => 9,
                'director' => 'Denis Villeneuve',
                'release_year' => 2016,
                'duration' => 116,
                'rate' => 7.9,
                'img_path' => 'img/arrival.jpg',
                'video_path' => 'tFMo3UJ4B4g',
                'price_day' => 11.00,
                'available' => 'dostępny'
            ],
            [
                'title' => 'Django Unchained',
                'description' => 'Django, uwolniony niewolnik, wyrusza, aby uwolnić swoją żonę z rąk brutalnego plantatora w przedwojennym Missisipi.',
                'category_id' => 1,
                'director' => 'Quentin Tarantino',
                'release_year' => 2012,
                'duration' => 165,
                'rate' => 8.4,
                'img_path' => 'img/django_unchained.jpg',
                'video_path' => '0fUCuvNlOCg',
                'price_day' => 13.00,
                'available' => 'dostępny'
            ],
            [
                'title' => 'The Prestige',
                'description' => 'Dwaj rywalizujący magicy, każdy z obsesją na punkcie odkrycia tajemnic konkurencji, angażują się w rywalizację prowadzącą do tragedii.',
                'category_id' => 2,
                'director' => 'Christopher Nolan',
                'release_year' => 2006,
                'duration' => 130,
                'rate' => 8.5,
                'img_path' => 'img/the_prestige.jpg',
                'video_path' => 'o4gHCmTQDVI',
                'price_day' => 10.00,
                'available' => 'dostępny'
            ],
            [
                'title' => 'The Grand Budapest Hotel',
                'description' => 'Historia słynnego europejskiego hotelu między dwoma wojnami światowymi i jego lojalnego pracownika, który staje się najbliższym przyjacielem klienta.',
                'category_id' => 2,
                'director' => 'Wes Anderson',
                'release_year' => 2014,
                'duration' => 99,
                'rate' => 8.1,
                'img_path' => 'img/the_grand_budapest_hotel.jpg',
                'video_path' => '1Fg5iWmQjwk',
                'price_day' => 9.00,
                'available' => 'dostępny'
            ],
            [
                'title' => 'Her',
                'description' => 'W przyszłości, samotny pisarz zakochuje się w inteligentnym systemie operacyjnym zaprojektowanym, aby spełniać wszystkie jego potrzeby.',
                'category_id' => 9,
                'director' => 'Spike Jonze',
                'release_year' => 2013,
                'duration' => 126,
                'rate' => 8.0,
                'img_path' => 'img/her.jpg',
                'video_path' => 'ne6p6MfLBxc',
                'price_day' => 11.00,
                'available' => 'dostępny'
            ],
            [
                'title' => 'Gone Girl',
                'description' => 'Gdy jego żona znika w tajemniczych okolicznościach, mężczyzna staje się głównym podejrzanym w sprawie jej zniknięcia.',
                'category_id' => 18,
                'director' => 'David Fincher',
                'release_year' => 2014,
                'duration' => 149,
                'rate' => 8.1,
                'img_path' => 'img/gone_girl.jpg',
                'video_path' => '2-_-1nJf8Vg',
                'price_day' => 12.00,
                'available' => 'dostępny'
            ],
            [
                'title' => 'Ex Machina',
                'description' => 'Młody programista bierze udział w eksperymencie dotyczącym sztucznej inteligencji, testując możliwości zaawansowanego robota.',
                'category_id' => 9,
                'director' => 'Alex Garland',
                'release_year' => 2014,
                'duration' => 108,
                'rate' => 7.7,
                'img_path' => 'img/ex_machina.jpg',
                'video_path' => 'V85VqlVptWM',
                'price_day' => 10.00,
                'available' => 'dostępny'
            ],
            [
                'title' => 'Parasite',
                'description' => 'Członkowie ubogiej rodziny systematycznie infiltrują się w życie bogatej rodziny koreańskiej.',
                'category_id' => 18,
                'director' => 'Bong Joon-ho',
                'release_year' => 2019,
                'duration' => 132,
                'rate' => 8.6,
                'img_path' => 'img/parasite.jpg',
                'video_path' => '5xH0HfJHsaY',
                'price_day' => 12.00,
                'available' => 'dostępny'
            ],
            [
                'title' => 'The Irishman',
                'description' => 'Stary gangster opowiada historię swojego życia, skupiając się na swojej roli w zniknięciu Jimmy’ego Hoffy.',
                'category_id' => 18,
                'director' => 'Martin Scorsese',
                'release_year' => 2019,
                'duration' => 209,
                'rate' => 7.9,
                'img_path' => 'img/the_irishman.jpg',
                'video_path' => 'RS3aHkkfuEI',
                'price_day' => 11.00,
                'available' => 'dostępny'
            ],
            [
                'title' => '1917',
                'description' => 'Podczas I wojny światowej, dwaj brytyjscy żołnierze otrzymują zadanie dostarczenia wiadomości głęboko na teren wroga, co może uratować życie tysięcy.',
                'category_id' => 15,
                'director' => 'Sam Mendes',
                'release_year' => 2019,
                'duration' => 119,
                'rate' => 8.3,
                'img_path' => 'img/1917.jpg',
                'video_path' => 'gZjQROMAh_s',
                'price_day' => 10.00,
                'available' => 'dostępny'
            ],
            [
                'title' => 'Joker',
                'description' => 'W Gotham City, zmagający się z problemami psychicznymi komik Arthur Fleck przekształca się w przestępczą postać znaną jako Joker.',
                'category_id' => 18,
                'director' => 'Todd Phillips',
                'release_year' => 2019,
                'duration' => 122,
                'rate' => 8.5,
                'img_path' => 'img/joker.jpg',
                'video_path' => 'zAGVQLHvwOY',
                'price_day' => 13.00,
                'available' => 'dostępny'
            ],
            [
                'title' => 'Once Upon a Time in Hollywood',
                'description' => 'Alternatywna historia Hollywood końca lat 60., skupiająca się na starzejącym się aktorze i jego kaskaderze.',
                'category_id' => 1,
                'director' => 'Quentin Tarantino',
                'release_year' => 2019,
                'duration' => 161,
                'rate' => 7.6,
                'img_path' => 'img/once_upon_a_time_in_hollywood.jpg',
                'video_path' => 'ELeMaP8EPAA',
                'price_day' => 12.00,
                'available' => 'dostępny'
            ],
            [
                'title' => 'Knives Out',
                'description' => 'Detektyw Benoit Blanc rozwiązuję zagadkę morderstwa słynnego pisarza podczas jego urodzinowego przyjęcia.',
                'category_id' => 18,
                'director' => 'Rian Johnson',
                'release_year' => 2019,
                'duration' => 130,
                'rate' => 7.9,
                'img_path' => 'img/knives_out.jpg',
                'video_path' => 'qGqiHJTsRkQ',
                'price_day' => 10.00,
                'available' => 'dostępny'
            ],
            [
                'title' => 'Little Women',
                'description' => 'Adaptacja klasycznej powieści, opowiadająca historię czterech sióstr dorastających po wojnie secesyjnej w Ameryce.',
                'category_id' => 6,
                'director' => 'Greta Gerwig',
                'release_year' => 2019,
                'duration' => 135,
                'rate' => 7.8,
                'img_path' => 'img/little_women.webp',
                'video_path' => 'AST2-4db4ic',
                'price_day' => 9.00,
                'available' => 'dostępny'
            ],
            [
                'title' => 'Marriage Story',
                'description' => 'Film opowiada o procesie rozwodowym pomiędzy reżyserem teatralnym a jego aktorką, badając złożoność rozpadu związku i wspólnego rodzicielstwa.',
                'category_id' => 3,
                'director' => 'Noah Baumbach',
                'release_year' => 2019,
                'duration' => 137,
                'rate' => 8.0,
                'img_path' => 'img/marriage_story.jpg',
                'video_path' => 'BHi-a1n8t7M',
                'price_day' => 11.00,
                'available' => 'dostępny'
            ],
            [
                'title' => 'Ford v Ferrari',
                'description' => 'Opowieść o zespole inżynierów i projektantów z Forda, którzy mają za zadanie zbudować samochód zdolny pokonać Ferrari na 24-godzinnym wyścigu w Le Mans w 1966 roku.',
                'category_id' => 5,
                'director' => 'James Mangold',
                'release_year' => 2019,
                'duration' => 152,
                'rate' => 8.1,
                'img_path' => 'img/ford_v_ferrari.jpg',
                'video_path' => 'I3h9Z89U9ZA',
                'price_day' => 10.00,
                'available' => 'dostępny'
            ],
            [
                'title' => 'Jojo Rabbit',
                'description' => 'Satyra wojenna o chłopcu z Hitlerjugend, który odkrywa, że jego matka ukrywa młodą Żydówkę na strychu.',
                'category_id' => 1,
                'director' => 'Taika Waititi',
                'release_year' => 2019,
                'duration' => 108,
                'rate' => 7.9,
                'img_path' => 'img/jojo_rabbit.png',
                'video_path' => 'tL4McUzXfFI',
                'price_day' => 9.00,
                'available' => 'dostępny'
            ],
            [
                'title' => 'Tenet',
                'description' => 'Tajny agent zostaje wciągnięty w świat szpiegostwa międzynarodowego, gdzie czas płynie inaczej.',
                'category_id' => 9,
                'director' => 'Christopher Nolan',
                'release_year' => 2020,
                'duration' => 150,
                'rate' => 7.4,
                'img_path' => 'img/tenet.jpg',
                'video_path' => 'L3pk_TBkihU',
                'price_day' => 14.00,
                'available' => 'dostępny'
            ],
            [
                'title' => 'Dune',
                'description' => 'Młody arystokrata musi chronić najcenniejszy zasób i najniebezpieczniejszy element we wszechświecie.',
                'category_id' => 9,
                'director' => 'Denis Villeneuve',
                'release_year' => 2021,
                'duration' => 155,
                'rate' => 8.0,
                'img_path' => 'img/dune.webp',
                'video_path' => 'n9xhJrPXop4',
                'price_day' => 15.00,
                'available' => 'dostępny'
            ],
            [
                'title' => 'Mulan',
                'description' => 'Młoda kobieta podszywa się pod mężczyznę, aby walczyć w armii cesarskiej.',
                'category_id' => 7,
                'director' => 'Niki Caro',
                'release_year' => 2020,
                'duration' => 115,
                'rate' => 5.7,
                'img_path' => 'img/mulan.jpg',
                'video_path' => 'KK8FHdFluOQ',
                'price_day' => 12.00,
                'available' => 'dostępny'
            ],
            [
                'title' => 'Soul',
                'description' => 'Nauczyciel muzyki marzący o karierze jazzowej ma wypadek, który oddziela jego duszę od ciała.',
                'category_id' => 12,
                'director' => 'Pete Docter',
                'release_year' => 2020,
                'duration' => 100,
                'rate' => 8.1,
                'img_path' => 'img/soul.jpg',
                'video_path' => 'xOsLIiBStEs',
                'price_day' => 9.00,
                'available' => 'dostępny'
            ],
            [
                'title' => 'Wonder Woman 1984',
                'description' => 'Diana Prince wchodzi w konflikt z dwoma wielkimi wrogami podczas zimnej wojny.',
                'category_id' => 1,
                'director' => 'Patty Jenkins',
                'release_year' => 2020,
                'duration' => 151,
                'rate' => 5.4,
                'img_path' => 'img/wonder_woman_1984.jpg',
                'video_path' => 'sfM7_JLk-84',
                'price_day' => 13.00,
                'available' => 'dostępny'
            ],
            [
                'title' => 'The Trial of the Chicago 7',
                'description' => 'Opowieść o siedmiu osobach oskarżonych o różne zarzuty w związku z powstaniem na konwencji narodowej w 1968 roku.',
                'category_id' => 18,
                'director' => 'Aaron Sorkin',
                'release_year' => 2020,
                'duration' => 129,
                'rate' => 7.8,
                'img_path' => 'img/the_trial_of_the_chicago_7.jpg',
                'video_path' => 'FVb6EdKDBfU',
                'price_day' => 10.00,
                'available' => 'dostępny'
            ],
            [
                'title' => 'No Time to Die',
                'description' => 'James Bond opuszcza spokojne życie na Jamajce, aby uratować porwanego naukowca.',
                'category_id' => 1,
                'director' => 'Cary Joji Fukunaga',
                'release_year' => 2021,
                'duration' => 163,
                'rate' => 7.3,
                'img_path' => 'img/no_time_to_die.jpg',
                'video_path' => 'vw2FOYjCz38',
                'price_day' => 14.00,
                'available' => 'dostępny'
            ],
            [
                'title' => 'A Quiet Place Part II',
                'description' => 'Rodzina Abbott musi stawić czoła strachom świata zewnętrznego, kontynuując walkę o przetrwanie w ciszy.',
                'category_id' => 5,
                'director' => 'John Krasinski',
                'release_year' => 2021,
                'duration' => 97,
                'rate' => 7.3,
                'img_path' => 'img/a_quiet_place_part_ii.jpg',
                'video_path' => 'BpdDN9d9Jio',
                'price_day' => 10.00,
                'available' => 'dostępny'
            ],
            [
                'title' => 'Raya and the Last Dragon',
                'description' => 'Młoda wojowniczka Raya musi znaleźć ostatniego smoka, aby uratować swój świat przed dawno zapomnianym złem.',
                'category_id' => 7,
                'director' => 'Don Hall, Carlos López Estrada',
                'release_year' => 2021,
                'duration' => 107,
                'rate' => 7.4,
                'img_path' => 'img/raya_and_the_last_dragon.jpg',
                'video_path' => '1VIZ89FEjYI',
                'price_day' => 10.00,
                'available' => 'dostępny'
            ],
            [
                'title' => 'The Father',
                'description' => 'Starzejący się mężczyzna odrzuca wszystkie proponowane mu pomocniki, gdy próbuje zrozumieć swoją zmieniającą się rzeczywistość.',
                'category_id' => 3,
                'director' => 'Florian Zeller',
                'release_year' => 2020,
                'duration' => 97,
                'rate' => 8.3,
                'img_path' => 'img/the_father.jpg',
                'video_path' => '4TZb7YfK-JI',
                'price_day' => 11.00,
                'available' => 'dostępny'
            ],
            [
                'title' => 'Marvel Legends',
                'description' => 'Seria dokumentalna od Marvel Studios, eksplorująca postacie i wydarzenia z uniwersum Marvela.',
                'category_id' => 9, 
                'director' => 'Różni',
                'release_year' => 2021,
                'duration' => 50,
                'rate' => 7.8,
                'img_path' => 'img/marvel_legends.webp',
                'video_path' => 'lWQF6F81kbY',
                'price_day' => 10.00,
                'available' => 'dostępny'
            ],
            [
                'title' => 'The Simpsons',
                'description' => 'Długo emitowany serial animowany opowiadający o perypetiach rodziny Simpsonów.',
                'category_id' => 11, 
                'director' => 'Matt Groening',
                'release_year' => 1989,
                'duration' => 22,
                'rate' => 8.7,
                'img_path' => 'img/the_simpsons.jpg',
                'video_path' => 'XPG0MqIcby8', 
                'price_day' => 5.00,
                'available' => 'dostępny'
            ],
            [
                'title' => 'Marvel Avengers',
                'description' => 'Superbohaterowie zjednoczeni, aby powstrzymać Thanosa przed zniszczeniem połowy Wszechświata.',
                'category_id' => 1,
                'director' => 'Joss Whedon',
                'release_year' => 2012,
                'duration' => 143,
                'rate' => 8.1,
                'img_path' => 'img/marvel_avengers.jpg',
                'video_path' => 'eOrNdBpGMv8',
                'price_day' => 15.00,
                'available' => 'dostępny'
            ],
            [
                'title' => 'Burrow',
                'description' => 'Krótkometrażowy film animowany o króliku budującym swoją wymarzoną norę.',
                'category_id' => 11, 
                'director' => 'Madeline Sharafian',
                'release_year' => 2020,
                'duration' => 6,
                'rate' => 7.8,
                'img_path' => 'img/burrow.jpg',
                'video_path' => 'apx1aUP3MqA',
                'price_day' => 3.00,
                'available' => 'dostępny'
            ]            
        ]);
    }
}